# Generated by Django 4.1.7 on 2023-04-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0004_delete_transfer_alter_feed_feedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
    ]
