# Generated by Django 4.1.7 on 2023-04-02 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0005_cards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cards',
        ),
    ]
